---
cog_bundle_version: 4
name: datadog
description: Interact with datadog graphs
version: 0.1.0
docker:
  image: cogcmd/datadog
  tag: 0.1.0
commands:
  dashboard-list:
    executable: "/home/bundle/cog-command"
    description: Lists dashboards
    arguments: "[time-range] <snapshot-query>"
    rules:
    - allow
  metric-search:
    executable: "/home/bundle/cog-command"
    description: Search for metrics
    arguments: "<metric-name>"
    rules:
    - allow
  graph:
    executable: "/home/bundle/cog-command"
    description: Generates a graph from a metric query
    rules:
    - allow
templates:
  metric_search:
    body: |
      ~each var=$results as=metric~
      * ~$metric.name~
      ~end~
  graph:
    body: |
      ~each var=$results as=graph~
      ~$graph.snapshot_url~
      ~end~
